# Generated by Django 4.0.1 on 2022-03-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_movie_age_limit_alter_movie_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='type',
            field=models.CharField(choices=[('Seasonal', 'Seasonal'), ('Single', 'Single')], max_length=10),
        ),
    ]
